// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbyahhrbpqjtzxbjdipd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBieWFoaHJicHFqdHp4YmpkaXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzkyMzgsImV4cCI6MjA3MDUxNTIzOH0.3S5I4XzSDVP8eHipCNRDrWEm9QvIO0-EiLlZ1F7oCb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});